version: '3.9'

services:
  example-server-app:
    build: 
      context: ../..
      dockerfile: samples/BlazorServer/Dockerfile
    ports:
      - "5001:443"
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_ENVIRONMENT=Production